DROP TABLE IF EXISTS User;
CREATE TABLE User (
id INT UNSIGNED NOT NULL PRIMARY KEY, 
first_name VARCHAR(32) DEFAULT NULL, 
last_name VARCHAR(32) DEFAULT NULL,
password VARCHAR(100) DEFAULT NULL,
username VARCHAR (20) DEFAULT NULL

);

DROP TABLE IF EXISTS Menu;
CREATE TABLE Menu (
id INT UNSIGNED NOT NULL PRIMARY KEY,
body VARCHAR(1000) DEFAULT NULL,
subject VARCHAR(50) DEFAULT NULL,
user_id VARCHAR(32) DEFAULT NULL,
recipient_ids VARCHAR(32) DEFAULT NULL

);


DROP TABLE IF EXISTS Message_read;
CREATE TABLE Message_read (
id INT UNSIGNED NOT NULL PRIMARY KEY, 
message_id VARCHAR(32) DEFAULT NULL, 
reader_id VARCHAR DEFAULT NULL,
date VARCHAR(20) DEFAULT NULL

);