DROP TABLE IF EXISTS User;
CREATE TABLE User (
id INT UNSIGNED NOT NULL PRIMARY KEY, 
first_name VARCHAR(32) DEFAULT NULL, 
last_name VARCHAR(32) DEFAULT NULL,
password VARCHAR(100) DEFAULT NULL,
username VARCHAR (20) DEFAULT NULL

);